---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${MOLECULE_PLATFORM:-debian9}"
    image: "jdubz/docker-ci-${MOLECULE_IMAGE:-debian:stretch-slim}"
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    env:
      LC_ALL: en_US.UTF-8
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
